devices:
  - modbus:
      url: __HOST__:__PORT__ # device url (mandatory)
      timeout: 10 # communication timeout (s) (optional, default: 10)
      connection_time: 0.1 # delay after connection (s) (optional, default: 0)
    listen:
      bind: 0:__LISTENPORT__ # listening address (mandatory)
