name: "modbus-proxy"
description: "Proxy for Accessing modbus systems. Allows multiple client connections"
version: "1.0.12"
slug: "modbus_proxy"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
url: "https://community.home-assistant.io/t/updated-solaredge-modbus-full-setup-guide-with-energy-dashboard-integration-for-installations-with-battery-connected/340956/216?u=akulatraxas"
startup: services
options:
  upstreamhost: "192.168.178.74"
  upstreamport: 502
  listenport: 502
schema:
  upstreamhost: str
  upstreamport: int
  listenport: int
ports:
  502/tcp: 502
