name: "modbus-test"
description: "My first real add-on!"
version: "1.0.11"
slug: "modbus_proxy_test"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
options:
  upstreamhost: "192.168.178.74"
  upstreamport: 502
  listenport: 502
schema:
  upstreamhost: str
  upstreamport: int
  listenport: int
ports:
  502/tcp: 502
